/**
 * Curadoria de Google Fonts (SIL OFL / Apache / Ubuntu Font License).
 * Não incluímos as ~1500 famílias para não inflar o bundle nem travar o UI;
 * a lista cobre as mais usadas em marca e anúncios. Ver https://fonts.google.com
 *
 * `family` = nome exato da família na API Google Fonts (espaços permitidos).
 * `tags` = palavras-chave para a busca no combobox.
 */
export const NEURODESIGN_GOOGLE_FONTS = [
  { family: 'Roboto', tags: 'sans neo grotesque' },
  { family: 'Open Sans', tags: 'sans humanist' },
  { family: 'Lato', tags: 'sans humanist' },
  { family: 'Montserrat', tags: 'sans geometric' },
  { family: 'Poppins', tags: 'sans geometric' },
  { family: 'Inter', tags: 'sans ui' },
  { family: 'Nunito', tags: 'sans rounded' },
  { family: 'Raleway', tags: 'sans elegant' },
  { family: 'Ubuntu', tags: 'sans linux' },
  { family: 'Merriweather', tags: 'serif legível' },
  { family: 'Playfair Display', tags: 'serif elegante' },
  { family: 'Lora', tags: 'serif' },
  { family: 'PT Serif', tags: 'serif' },
  { family: 'Source Serif 4', tags: 'serif adobe' },
  { family: 'Libre Baskerville', tags: 'serif clássica' },
  { family: 'Oswald', tags: 'sans condensed' },
  { family: 'Bebas Neue', tags: 'sans display' },
  { family: 'Anton', tags: 'sans display' },
  { family: 'Barlow', tags: 'sans' },
  { family: 'Work Sans', tags: 'sans' },
  { family: 'Rubik', tags: 'sans' },
  { family: 'Mulish', tags: 'sans' },
  { family: 'Quicksand', tags: 'sans rounded' },
  { family: 'DM Sans', tags: 'sans' },
  { family: 'Manrope', tags: 'sans' },
  { family: 'Outfit', tags: 'sans geometric' },
  { family: 'Plus Jakarta Sans', tags: 'sans' },
  { family: 'Figtree', tags: 'sans' },
  { family: 'Lexend', tags: 'sans legível' },
  { family: 'Fira Sans', tags: 'sans mozilla' },
  { family: 'Noto Sans', tags: 'sans unicode' },
  { family: 'Noto Serif', tags: 'serif unicode' },
  { family: 'Cabin', tags: 'sans' },
  { family: 'Karla', tags: 'sans' },
  { family: 'Josefin Sans', tags: 'sans geometric' },
  { family: 'Arimo', tags: 'sans' },
  { family: 'Titillium Web', tags: 'sans' },
  { family: 'Exo 2', tags: 'sans tech' },
  { family: 'Kanit', tags: 'sans' },
  { family: 'Sora', tags: 'sans' },
  { family: 'Space Grotesk', tags: 'sans tech' },
  { family: 'Archivo', tags: 'sans' },
  { family: 'IBM Plex Sans', tags: 'sans corporate' },
  { family: 'IBM Plex Serif', tags: 'serif corporate' },
  { family: 'Red Hat Display', tags: 'sans' },
  { family: 'Bitter', tags: 'serif' },
  { family: 'Crimson Pro', tags: 'serif' },
  { family: 'EB Garamond', tags: 'serif clássica' },
  { family: 'Cormorant Garamond', tags: 'serif elegante' },
  { family: 'Abril Fatface', tags: 'serif display' },
  { family: 'Alfa Slab One', tags: 'serif display' },
  { family: 'Bungee', tags: 'sans display' },
  { family: 'Righteous', tags: 'sans display' },
  { family: 'Pacifico', tags: 'script casual' },
  { family: 'Dancing Script', tags: 'script' },
  { family: 'Caveat', tags: 'script manuscrito' },
  { family: 'Satisfy', tags: 'script' },
  { family: 'Great Vibes', tags: 'script elegante' },
  { family: 'Permanent Marker', tags: 'display informal' },
  { family: 'Press Start 2P', tags: 'pixel retro' },
  { family: 'Orbitron', tags: 'sans futurista' },
  { family: 'Teko', tags: 'sans condensed' },
  { family: 'Staatliches', tags: 'sans display' },
  { family: 'Fjalla One', tags: 'sans condensed' },
  { family: 'Heebo', tags: 'sans' },
  { family: 'Varela Round', tags: 'sans rounded' },
  { family: 'Comfortaa', tags: 'sans rounded' },
  { family: 'Signika Negative', tags: 'sans' },
  { family: 'Asap', tags: 'sans' },
  { family: 'Catamaran', tags: 'sans' },
  { family: 'Hind', tags: 'sans' },
  { family: 'Mukta', tags: 'sans' },
  { family: 'Tinos', tags: 'serif times' },
  { family: 'Spectral', tags: 'serif' },
  { family: 'Zilla Slab', tags: 'serif mozilla' },
  { family: 'Recursive', tags: 'sans variable' },
  { family: 'Chakra Petch', tags: 'sans tech' },
  { family: 'Saira', tags: 'sans' },
  { family: 'Public Sans', tags: 'sans gov' },
];
